"""Core utilities and server components for VFX MCP."""

from .media import (
    DEFAULT_AUDIO_CODEC,
    DEFAULT_VIDEO_CODEC,
    FORMAT_CODECS,
    TARGET_CHANNEL_LAYOUT,
    TARGET_SAMPLE_RATE,
    XFADE_TRANSITION_MAP,
    even_dimension,
    normalize_audio_stream,
    normalize_video_stream,
    silent_audio_source,
)
from .utilities import (
    COLOR_MAP,
    create_standard_output,
    get_video_metadata,
    handle_ffmpeg_error,
    log_operation,
    parse_color,
    parse_resolution,
    parse_size_range,
    run_ffmpeg_async,
)
from .validation import (
    resolve_workspace,
    safe_input_path,
    safe_output_path,
    validate_animation_type,
    validate_file_path,
    validate_filter_name,
    validate_output_path,
    validate_range,
    validate_transition_type,
    validate_video_paths,
)

__all__ = [
    "handle_ffmpeg_error",
    "run_ffmpeg_async",
    "log_operation",
    "get_video_metadata",
    "create_standard_output",
    "parse_color",
    "parse_resolution",
    "parse_size_range",
    "resolve_workspace",
    "safe_input_path",
    "safe_output_path",
    "validate_range",
    "validate_file_path",
    "validate_filter_name",
    "validate_animation_type",
    "validate_transition_type",
    "validate_output_path",
    "validate_video_paths",
    "COLOR_MAP",
    "even_dimension",
    "normalize_video_stream",
    "normalize_audio_stream",
    "silent_audio_source",
    "TARGET_SAMPLE_RATE",
    "TARGET_CHANNEL_LAYOUT",
    "XFADE_TRANSITION_MAP",
    "FORMAT_CODECS",
    "DEFAULT_VIDEO_CODEC",
    "DEFAULT_AUDIO_CODEC",
]
